openapi: 3.1.0
info:
  title: API
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /auth/signup:
    $ref: './components/authentication.yaml#/paths/~1signup'
  /auth/signin:
    $ref: './components/authentication.yaml#/paths/~1signin'
  /auth/refresh-token:
    $ref: './components/authentication.yaml#/paths/~1refresh-token'

  /ai-agent/agents:
    $ref: './components/ai-agent.yaml#/paths/~1agents'
  /ai-agent/agents/{agentId}:
    $ref: './components/ai-agent.yaml#/paths/~1agents~1{agentId}'
  /ai-agent/users/{userId}/agents/relations:
    $ref: './components/ai-agent.yaml#/paths/~1users~1{userId}~1agents~1relations'

  /audit/events:
    $ref: './components/audit.yaml#/paths/~1events'

  # ML AI Service
  /ml/users/{userId}/session:
    $ref: './components/ml-service.yaml#/paths/~1users~1{userId}~1session'
  /ml/users/{userId}/session/settings:
    $ref: './components/ml-service.yaml#/paths/~1users~1{userId}~1session~1settings'
  /ml/users/{userId}/messages:
    $ref: './components/ml-service.yaml#/paths/~1users~1{userId}~1messages'
  /ml/users/{userId}/conversation:
    $ref: './components/ml-service.yaml#/paths/~1users~1{userId}~1conversation'

components:
  schemas:
    ErrorCode:
      $ref: './components/errors.yaml#/components/schemas/ErrorCode'
    ErrorResponse:
      $ref: './components/errors.yaml#/components/schemas/ErrorResponse'
    SignUpDto:
      $ref: './components/authentication.yaml#/components/schemas/SignUpDto'
    SignInDto:
      $ref: './components/authentication.yaml#/components/schemas/SignInDto'
    
    AiAgentDto:
      $ref: './components/ai-agent.yaml#/components/schemas/AiAgentDto'
    AgentTraits:
      $ref: './components/ai-agent.yaml#/components/schemas/AgentTraits'
    PersonalityType:
      $ref: './components/ai-agent.yaml#/components/schemas/PersonalityType'
    
    # Audit Service schemas
    AuditEvent:
      $ref: './components/audit.yaml#/components/schemas/AuditEvent'
    AuditSourceAgent:
      $ref: './components/audit.yaml#/components/schemas/SourceAgent'
    AuditTargetAgent:
      $ref: './components/audit.yaml#/components/schemas/TargetAgent'
    AuditMood:
      $ref: './components/audit.yaml#/components/schemas/Mood'
    AuditSimulationContext:
      $ref: './components/audit.yaml#/components/schemas/SimulationContext'

    # ML AI Service schemas
    SessionCreateRequest:
      $ref: './components/ml-service.yaml#/components/schemas/SessionCreateRequest'
    SessionSettingsRequest:
      $ref: './components/ml-service.yaml#/components/schemas/SessionSettingsRequest'
    SessionSettingsResponse:
      $ref: './components/ml-service.yaml#/components/schemas/SessionSettingsResponse'
    SessionInfo:
      $ref: './components/ml-service.yaml#/components/schemas/SessionInfo'
    MessageRequest:
      $ref: './components/ml-service.yaml#/components/schemas/MessageRequest'
    MessageResponse:
      $ref: './components/ml-service.yaml#/components/schemas/MessageResponse'
    ConversationResponse:
      $ref: './components/ml-service.yaml#/components/schemas/ConversationResponse'

  responses:
    BadRequest:
      $ref: './components/authentication.yaml#/components/responses/BadRequest'
    Conflict:
      $ref: './components/authentication.yaml#/components/responses/Conflict'
    TooManyRequests:
      $ref: './components/authentication.yaml#/components/responses/TooManyRequests'
    Unauthorized:
      $ref: './components/authentication.yaml#/components/responses/Unauthorized'
    InternalError:
      $ref: './components/authentication.yaml#/components/responses/InternalError'