openapi: 3.1.0
info:
  title: API
  version: 1.0.0

servers:
  - url: /api/v1

paths:
  /auth/signup:
    $ref: './components/authentication.yaml#/paths/~1signup'
  /auth/signin:
    $ref: './components/authentication.yaml#/paths/~1signin'
  /auth/refresh-token:
    $ref: './components/authentication.yaml#/paths/~1refresh-token'

  /ai-agent/agents:
    $ref: './components/ai-agent.yaml#/paths/~1agents'
  /ai-agent/agents/{agentId}:
    $ref: './components/ai-agent.yaml#/paths/~1agents~1{agentId}'
  /ai-agent/users/{userId}/agents/relations:
    $ref: './components/ai-agent.yaml#/paths/~1users~1{userId}~1agents~1relations'

  /audit/events:
    $ref: './components/audit.yaml#/paths/~1events'

components:
  schemas:
    ErrorCode:
      $ref: './components/errors.yaml#/components/schemas/ErrorCode'
    ErrorResponse:
      $ref: './components/errors.yaml#/components/schemas/ErrorResponse'
    SignUpDto:
      $ref: './components/authentication.yaml#/components/schemas/SignUpDto'
    SignInDto:
      $ref: './components/authentication.yaml#/components/schemas/SignInDto'
    
    AiAgentDto:
      $ref: './components/ai-agent.yaml#/components/schemas/AiAgentDto'
    AgentTraits:
      $ref: './components/ai-agent.yaml#/components/schemas/AgentTraits'
    PersonalityType:
      $ref: './components/ai-agent.yaml#/components/schemas/PersonalityType'
    
    AiAgent:
      $ref: './components/audit.yaml#/components/schemas/AiAgent'

  responses:
    BadRequest:
      $ref: './components/authentication.yaml#/components/responses/BadRequest'
    Conflict:
      $ref: './components/authentication.yaml#/components/responses/Conflict'
    TooManyRequests:
      $ref: './components/authentication.yaml#/components/responses/TooManyRequests'
    Unauthorized:
      $ref: './components/authentication.yaml#/components/responses/Unauthorized'
    InternalError:
      $ref: './components/authentication.yaml#/components/responses/InternalError'