openapi: 3.1.0
info:
  title: Audit Service
  version: 2.0.0

servers:
  - url: /api/v1/audit

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: JWT токен аутентификации (содержит userId)

  schemas:
    Mood:
      type: object
      description: Настроение агента
      properties:
        dominant_emotion:
          type: string
          description: Доминирующая эмоция
          examples:
            - "спокойствие"
            - "решимость"
            - "тревога"
        happiness:
          type: number
          format: float
          minimum: -1
          maximum: 1
          description: Уровень счастья
        energy:
          type: number
          format: float
          minimum: -1
          maximum: 1
          description: Уровень энергии
        stress:
          type: number
          format: float
          minimum: -1
          maximum: 1
          description: Уровень стресса
        anger:
          type: number
          format: float
          minimum: -1
          maximum: 1
          description: Уровень злости
        fear:
          type: number
          format: float
          minimum: -1
          maximum: 1
          description: Уровень страха

    Relationship:
      type: object
      description: Отношение к другому агенту
      properties:
        value:
          type: number
          format: float
          description: Значение отношения (-1.0 до 1.0)
          minimum: -1
          maximum: 1
        display_name:
          type: string
          description: Отображаемое имя агента

    Activity:
      type: object
      description: Активность агента
      properties:
        talkativeness:
          type: number
          format: float
          description: Уровень разговорчивости (0.0-1.0)
          minimum: 0
          maximum: 1
        messages_spoken:
          type: integer
          description: Количество сообщений за сессию
          minimum: 0

    Plan:
      type: object
      description: Текущий план агента
      properties:
        goal:
          type: string
          description: Текущая цель агента
          examples:
            - "Построить укрытие"
        current_step:
          type: integer
          description: Текущий шаг плана
          minimum: 0

    SourceAgent:
      type: object
      description: Агент-инициатор события (полное состояние)
      required:
        - agent_id
        - name
      properties:
        agent_id:
          type: string
          description: Уникальный ID агента
          examples:
            - "agent_1"
        name:
          type: string
          description: Имя агента
          examples:
            - "Алиса"
        mood:
          $ref: '#/components/schemas/Mood'
        relationships:
          type: object
          description: Отношения к другим агентам (ключ = agent_id)
          additionalProperties:
            $ref: '#/components/schemas/Relationship'
        activity:
          $ref: '#/components/schemas/Activity'
        plan:
          $ref: '#/components/schemas/Plan'

    TargetAgent:
      type: object
      description: Агент-получатель события
      required:
        - agent_id
        - name
      properties:
        agent_id:
          type: string
          description: ID агента-получателя
        name:
          type: string
          description: Имя агента-получателя

    SentimentChange:
      type: object
      description: Изменение отношения к агенту
      properties:
        delta:
          type: number
          format: float
          description: Изменение значения отношения
          examples:
            - 0.1
            - -0.05
        reason:
          type: string
          description: Причина изменения
          examples:
            - "позитив: 'спасибо'"
            - "негатив: 'глуп'"

    EventData:
      type: object
      description: Данные события
      properties:
        message:
          type: string
          description: Текст сообщения агента
          examples:
            - "Давайте построим укрытие из пальм!"
        tick:
          type: integer
          description: Номер тика симуляции
          minimum: 0
        is_initiative:
          type: boolean
          description: Агент инициировал действие/тему
        action_result:
          type: string
          nullable: true
          description: Результат действия (если было действие)
        sentiments:
          type: object
          description: Изменения отношений (ключ = agent_id получателя)
          additionalProperties:
            $ref: '#/components/schemas/SentimentChange'

    SimulationContext:
      type: object
      description: Контекст симуляции
      properties:
        scenario_name:
          type: string
          description: Название текущего сценария
          examples:
            - "Необитаемый остров"
        current_topic:
          type: string
          nullable: true
          description: Текущая тема обсуждения
          examples:
            - "как построить укрытие из пальм?"
        phase:
          type: string
          description: Текущая фаза диалога
          enum:
            - discuss
            - decide
            - act
            - conclude
          examples:
            - "decide"

    AuditEvent:
      type: object
      description: Полное событие аудита
      required:
        - event_type
        - source_agent
        - timestamp
      properties:
        event_type:
          type: string
          description: Тип события
          enum:
            - message_sent
            - new_topic
            - event_reaction
          examples:
            - "message_sent"
        source_agent:
          $ref: '#/components/schemas/SourceAgent'
        target_agents:
          type: array
          description: Агенты-получатели
          items:
            $ref: '#/components/schemas/TargetAgent'
        timestamp:
          type: string
          format: date-time
          description: Время события (ISO 8601)
          examples:
            - "2026-02-17T22:25:26.485Z"
        data:
          $ref: '#/components/schemas/EventData'
        simulation_context:
          $ref: '#/components/schemas/SimulationContext'

    # ── Ответы ──

    EventAcceptedResponse:
      type: object
      properties:
        status:
          type: string
          examples:
            - "accepted"
        type:
          type: string
          examples:
            - "message_sent"
        timestamp:
          type: string
          format: date-time

    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Описание ошибки
        details:
          type: string
          description: Детали ошибки

    # ── Feed / History ──

    Event:
      type: object
      description: Событие из ленты (с метаданными обработки)
      allOf:
        - $ref: '#/components/schemas/AuditEvent'
        - type: object
          properties:
            processed_at:
              type: string
              format: date-time
              description: Время обработки события
            processed_ts:
              type: integer
              format: int64
              description: Unix timestamp обработки

    EventsFeedResponse:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
        count:
          type: integer
          examples:
            - 10
        limit:
          type: integer
          examples:
            - 20
        source:
          type: string
          examples:
            - "redis"

    HistoryResponse:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
        count:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        total:
          type: integer
          description: Общее количество событий в БД
        source:
          type: string
          examples:
            - "postgresql"

    WebSocketStatsResponse:
      type: object
      properties:
        connected_clients:
          type: integer
          description: Количество подключенных клиентов

paths:
  /events:
    post:
      tags: [Audit Service]
      summary: Отправить событие в аудит
      description: |
        Отправляет полное событие симуляции в систему аудита.
        На каждом тике ML-сервис отправляет действия агентов в песочницу.
        
        JWT токен передаётся в заголовке Authorization и содержит userId.
      operationId: publishEvent
      security:
        - BearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuditEvent'
            example:
              event_type: "message_sent"
              source_agent:
                agent_id: "agent_1"
                name: "Алиса"
                mood:
                  dominant_emotion: "спокойствие"
                  happiness: 0.3
                  energy: 0.7
                  stress: 0.1
                  anger: 0.0
                  fear: 0.0
                relationships:
                  agent_2:
                    value: 0.15
                    display_name: "Борис"
                  agent_3:
                    value: -0.10
                    display_name: "Вика"
                activity:
                  talkativeness: 0.65
                  messages_spoken: 12
                plan:
                  goal: "Построить укрытие"
                  current_step: 2
              target_agents:
                - agent_id: "agent_2"
                  name: "Борис"
                - agent_id: "agent_3"
                  name: "Вика"
              timestamp: "2026-02-17T22:25:26.485Z"
              data:
                message: "Давайте построим укрытие из пальм!"
                tick: 5
                is_initiative: true
                action_result: null
                sentiments:
                  agent_2:
                    delta: 0.05
                    reason: "позитив: 'согласен'"
              simulation_context:
                scenario_name: "Необитаемый остров"
                current_topic: "как построить укрытие из пальм?"
                phase: "decide"
      responses:
        '202':
          description: Событие принято
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventAcceptedResponse'
        '400':
          description: Невалидный запрос
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован (невалидный или отсутствующий JWT)
        '429':
          description: Слишком много запросов
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /feed:
    get:
      tags: [Audit Service]
      summary: Получить ленту событий (из Redis)
      description: Получить последние события из Redis кеша
      security:
        - BearerAuth: []
      parameters:
        - name: limit
          in: query
          description: Количество событий (максимум 100)
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: Список последних событий
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsFeedResponse'
        '401':
          description: Не авторизован
        '500':
          description: Внутренняя ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /history:
    get:
      tags: [Audit Service]
      summary: Получить историю событий (из PostgreSQL)
      description: Получить события из PostgreSQL с пагинацией
      security:
        - BearerAuth: []
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 100
            minimum: 1
            maximum: 1000
        - name: offset
          in: query
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          description: Исторические события
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryResponse'
        '401':
          description: Не авторизован
        '500':
          description: Внутренняя ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /agents/{agent_id}/events:
    get:
      tags: [Audit Service]
      summary: Получить события агента
      description: Получить события конкретного агента
      security:
        - BearerAuth: []
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
        - name: limit
          in: query
          required: false
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 500
      responses:
        '200':
          description: События агента
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
                  count:
                    type: integer
                  limit:
                    type: integer
                  agent_id:
                    type: string
                  source:
                    type: string
                    examples:
                      - "postgresql"
        '400':
          description: Невалидный agent_id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован
        '500':
          description: Внутренняя ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /agents/{agent_id}/stats:
    get:
      tags: [Audit Service]
      summary: Получить статистику агента
      security:
        - BearerAuth: []
      parameters:
        - name: agent_id
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: Статистика агента
          content:
            application/json:
              schema:
                type: object
                properties:
                  agent_id:
                    type: string
                  total_events:
                    type: integer
                  messages_sent:
                    type: integer
                  last_activity:
                    type: string
                    format: date-time
                  event_types:
                    type: object
                    additionalProperties:
                      type: integer
        '400':
          description: Невалидный agent_id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '401':
          description: Не авторизован
        '500':
          description: Внутренняя ошибка
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /ws:
    get:
      tags: [Audit Service]
      summary: WebSocket подключение
      description: Real-time подписка на события через WebSocket
      responses:
        '101':
          description: Switching Protocols (WebSocket)
        '400':
          description: Bad Request

  /ws/stats:
    get:
      tags: [Audit Service]
      summary: Статистика WebSocket
      description: Количество подключенных клиентов
      responses:
        '200':
          description: Статистика WebSocket
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebSocketStatsResponse'
        '500':
          description: Внутренняя ошибка
