openapi: 3.1.0
info:
  title: Audit Service
  version: 1.0.0

servers:
  - url: /api/v1/audit

components:
  schemas:
    Mood:
      type: object
      properties:
        dominant_emotion:
          type: string
          examples: 
            - "спокойствие"
        happiness:
          type: number
          format: float
          minimum: 0
          maximum: 1
        energy:
          type: number
          format: float
          minimum: 0
          maximum: 1
        stress:
          type: number
          format: float
          minimum: 0
          maximum: 1
        anger:
          type: number
          format: float
          minimum: 0
          maximum: 1
        fear:
          type: number
          format: float
          minimum: 0
          maximum: 1
    
    Relationship:
      type: object
      properties:
        value:
          type: number
          format: float
          description: Значение отношения (-1.0 до 1.0)
          minimum: -1
          maximum: 1
        display_name:
          type: string
          description: Имя агента
    
    Activity:
      type: object
      properties:
        talkativeness:
          type: number
          format: float
          description: Уровень разговорчивости (0.0-1.0)
          minimum: 0
          maximum: 1
        messages_spoken:
          type: integer
          description: Количество сообщений
          minimum: 0
    
    Plan:
      type: object
      properties:
        goal:
          type: string
          description: Текущая цель
        current_step:
          type: integer
          description: Текущий шаг плана
          minimum: 0
    
    SourceAgent:
      type: object
      required:
        - agent_id
        - name
      properties:
        agent_id:
          type: string
          examples: 
            - "agent_1"
        name:
          type: string
          examples: 
            - "Алиса"
        mood:
          $ref: '#/components/schemas/Mood'
        relationships:
          type: object
          additionalProperties:
            $ref: '#/components/schemas/Relationship'
        activity:
          $ref: '#/components/schemas/Activity'
        plan:
          $ref: '#/components/schemas/Plan'
    
    TargetAgent:
      type: object
      required:
        - agent_id
      properties:
        agent_id:
          type: string
        name:
          type: string
    
    EventData:
      type: object
      properties:
        message:
          type: string
          description: Текст сообщения
        tick:
          type: integer
          description: Номер тика симуляции
          minimum: 0
        is_initiative:
          type: boolean
          description: Инициатор ли агент
        action_result:
          type: string
          description: Результат действия
        sentiments:
          type: object
          description: Изменения в отношениях
          additionalProperties:
            type: object
            properties:
              delta:
                type: number
                format: float
              reason:
                type: string
    
    SimulationContext:
      type: object
      properties:
        scenario_name:
          type: string
          examples: 
            - "Необитаемый остров"
        current_topic:
          type: string
        phase:
          type: string
          examples: 
            - "decide"
    Event:
      type: object
      description: Событие из ленты
      properties:
        event_type:
          type: string
          description: Тип события
        source_agent:
          $ref: '#/components/schemas/SourceAgent'
        target_agents:
          type: array
          items:
            $ref: '#/components/schemas/TargetAgent'
        timestamp:
          type: string
          format: date-time
          description: Время события
        data:
          $ref: '#/components/schemas/EventData'
        simulation_context:
          $ref: '#/components/schemas/SimulationContext'
        processed_at:
          type: string
          format: date-time
          description: Время обработки события
        processed_ts:
          type: integer
          format: int64
          description: Unix timestamp обработки
    
    ErrorResponse:
      type: object
      required:
        - error
      properties:
        error:
          type: string
          description: Описание ошибки
        details:
          type: string
          description: Детали ошибки

    EventsFeedResponse:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
        count:
          type: integer
          description: Количество возвращенных событий
          examples: 
            - 10
        limit:
          type: integer
          description: Запрошенный лимит
          examples:
            - 20
        source:
          type: string
          description: Источник данных
          examples:
            - "redis"

    HistoryResponse:
      type: object
      properties:
        events:
          type: array
          items:
            $ref: '#/components/schemas/Event'
        count:
          type: integer
        limit:
          type: integer
        offset:
          type: integer
        total:
          type: integer
          description: Общее количество событий в БД
        source:
          type: string
          examples:
            - "postgresql"

    EventAcceptedResponse:
      type: object
      properties:
        status:
          type: string
          examples:
            - "accepted"
        type:
          type: string
          examples:
            - "message_sent"
        timestamp:
          type: string
          format: date-time

    WebSocketStatsResponse:
      type: object
      properties:
        connected_clients:
          type: integer
          description: Количество подключенных клиентов

paths:
  /events:
    post:
      tags: [Audit Service]
      summary: Publish AI log
      description: Отправить событие в систему аудита
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - event_type
                - source_agent
                - timestamp
              properties:
                event_type:
                  type: string
                  description: Тип события
                  examples: 
                    - "message_sent"
                
                source_agent:
                  $ref: '#/components/schemas/SourceAgent'
                
                target_agents:
                  type: array
                  description: Агенты-получатели
                  items:
                    $ref: '#/components/schemas/TargetAgent'
                
                timestamp:
                  type: string
                  format: date-time
                  description: Время события
                
                data:
                  $ref: '#/components/schemas/EventData'
                
                simulation_context:
                  $ref: '#/components/schemas/SimulationContext'
      
      responses:
        '202':
          description: Event accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventAcceptedResponse'
        '400':
          description: Invalid request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '429':
          description: Too many requests
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /feed:
    get:
      tags: [Audit Service]
      summary: Get recent events feed (from Redis)
      description: Получить последние события из Redis кеша
      parameters:
        - name: limit
          in: query
          description: Количество событий (максимум 100)
          required: false
          schema:
            type: integer
            default: 20
            minimum: 1
            maximum: 100
      responses:
        '200':
          description: List of recent events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/EventsFeedResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /history:
    get:
      tags: [Audit Service]
      summary: Get historical events (from PostgreSQL)
      description: Получить события по агенту из PostgreSQL
      parameters:
        - name: limit
          in: query
          description: Количество событий (максимум 1000)
          required: false
          schema:
            type: integer
            default: 100
            minimum: 1
            maximum: 1000
        - name: offset
          in: query
          description: Смещение для пагинации
          required: false
          schema:
            type: integer
            default: 0
            minimum: 0
      responses:
        '200':
          description: Historical events
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/HistoryResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /agents/{agent_id}/events:
    get:
      tags: [Audit Service]
      summary: Get events by agent ID
      description: Получить события конкретного агента
      parameters:
        - name: agent_id
          in: path
          required: true
          description: ID агента
          schema:
            type: string
        - name: limit
          in: query
          description: Количество событий (максимум 500)
          required: false
          schema:
            type: integer
            default: 50
            minimum: 1
            maximum: 500
      responses:
        '200':
          description: Agent events
          content:
            application/json:
              schema:
                type: object
                properties:
                  events:
                    type: array
                    items:
                      $ref: '#/components/schemas/Event'
                  count:
                    type: integer
                    description: Количество возвращенных событий
                  limit:
                    type: integer
                    description: Запрошенный лимит
                  agent_id:
                    type: string
                    description: ID агента
                  source:
                    type: string
                    examples:
                      - "postgresql"
        '400':
          description: Invalid agent_id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'

  /agents/{agent_id}/stats:
    get:
      tags: [Audit Service]
      summary: Get agent statistics
      description: Получить статистику по агенту
      parameters:
        - name: agent_id
          in: path
          required: true
          description: ID агента
          schema:
            type: string
      responses:
        '200':
          description: Agent statistics
          content:
            application/json:
              schema:
                type: object
                properties:
                  agent_id:
                    type: string
                  total_events:
                    type: integer
                  messages_sent:
                    type: integer
                  last_activity:
                    type: string
                    format: date-time
                  event_types:
                    type: object
                    additionalProperties:
                      type: integer
        '400':
          description: Invalid agent_id
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /ws:
    get:
      tags: [Audit Service]
      summary: WebSocket connection
      description: Подключение к WebSocket для real-time событий
      responses:
        '101':
          description: Switching Protocols (WebSocket)
        '400':
          description: Bad Request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'
  
  /ws/stats:
    get:
      tags: [Audit Service]
      summary: WebSocket statistics
      description: Получить статистику WebSocket подключений
      responses:
        '200':
          description: WebSocket stats
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/WebSocketStatsResponse'
        '500':
          description: Internal server error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorResponse'