openapi: 3.1.0
info:
  title: Audit Service
  version: 1.0.0

servers:
  - url: /api/v1/audit
paths:
  /ai-agent-logs:
    post:
      tags: [AI Agent Logs] 
      summary: Publish AI log
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              properties: 
                id:
                  type: integer
                  format: uuid
                usernasme:
                  type: string
                  examples:
                    - ИИ агент Габена
                timestamp:
                  type: string
                  format: datetime
                type:
                  type: string # изменить, закинув в ML
                source:
                  type: integer
                  format: uuid
                  description: ИИ агент - инициатор общения
                target:
                  type: array
                  description: ИИ агент(ы) - получатели сообщения
                  items: 
                    type: string
                    format: uuid    
                data:
                  type: object
                  properties:
                    message:
                      type: string
                      examples:
                        - Я сварил пельмени
                    mood:
                      type: string # изменить, закинув в ML
                      examples: 
                        - happy
                
components:
  schemas: