openapi: 3.1.0
info:
  title: Audit Service
  version: 1.0.0

servers:
  - url: /api/v1/audit

components:
  schemas:
    AIAgent:
      type: object
      required:
        - id
        - username
      properties:
        id:
          type: string
          format: uuid
          description: Уникальный идентификатор агента
        username:
          type: string
          description: Имя агента
          examples:
            - ИИ агент Габена

paths:
  /events:
    post:
      tags: [AI Agent Logs]
      summary: Publish AI log
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
              properties:
                event_type:
                  type: string
                  description: Тип события для ML обработки
                source_agent:
                  $ref: '#/components/schemas/AIAgent'
                  description: ИИ агент - инициатор общения
                target_agents:
                  type: array
                  description: ИИ агент(ы) - получатели сообщения
                  items:
                    $ref: '#/components/schemas/AIAgent'
                timestamp:
                  type: string
                  format: date-time
                  description: Время события
                data:
                  type: object
                  description: Данные события
                  properties:
                    message:
                      type: string
                      description: Текст сообщения
                      examples:
                        - Я сварил пельмени
                    mood:
                      type: string
                      description: Настроение агента для ML обработки
                      examples:
                        - happy
                  required:
                    - message