// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AiAgent defines model for AiAgent.
type AiAgent struct {
	// Id Уникальный идентификатор агента
	Id openapi_types.UUID `json:"id"`

	// Username Имя агента
	Username string `json:"username"`
}

// Event Событие из ленты
type Event struct {
	// Data Данные события
	Data *struct {
		// Message Текст сообщения
		Message *string `json:"message,omitempty"`

		// Mood Настроение агента
		Mood *string `json:"mood,omitempty"`
	} `json:"data,omitempty"`

	// EventType Тип события
	EventType *string `json:"event_type,omitempty"`

	// ProcessedAt Время обработки события
	ProcessedAt *time.Time `json:"processed_at,omitempty"`

	// ProcessedTs Unix timestamp обработки
	ProcessedTs *int64   `json:"processed_ts,omitempty"`
	SourceAgent *AiAgent `json:"source_agent,omitempty"`

	// TargetAgents ИИ агенты - получатели
	TargetAgents *[]AiAgent `json:"target_agents,omitempty"`

	// Timestamp Время события
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// PostEventsJSONBody defines parameters for PostEvents.
type PostEventsJSONBody struct {
	// Data Данные события
	Data *struct {
		// Message Текст сообщения
		Message string `json:"message"`

		// Mood Настроение агента для ML обработки
		Mood *string `json:"mood,omitempty"`
	} `json:"data,omitempty"`

	// EventType Тип события для ML обработки
	EventType   *string  `json:"event_type,omitempty"`
	SourceAgent *AiAgent `json:"source_agent,omitempty"`

	// TargetAgents ИИ агент(ы) - получатели сообщения
	TargetAgents *[]AiAgent `json:"target_agents,omitempty"`

	// Timestamp Время события
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// GetFeedParams defines parameters for GetFeed.
type GetFeedParams struct {
	// Limit Количество событий (максимум 100)
	Limit *int `form:"limit,omitempty" json:"limit,omitempty"`
}

// PostEventsJSONRequestBody defines body for PostEvents for application/json ContentType.
type PostEventsJSONRequestBody PostEventsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Publish AI log
	// (POST /events)
	PostEvents(ctx echo.Context) error
	// Get recent events feed
	// (GET /feed)
	GetFeed(ctx echo.Context, params GetFeedParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostEvents converts echo context to params.
func (w *ServerInterfaceWrapper) PostEvents(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEvents(ctx)
	return err
}

// GetFeed converts echo context to params.
func (w *ServerInterfaceWrapper) GetFeed(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetFeedParams
	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameter("form", true, false, "limit", ctx.QueryParams(), &params.Limit)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetFeed(ctx, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/events", wrapper.PostEvents)
	router.GET(baseURL+"/feed", wrapper.GetFeed)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/9RXbWsbRxD+K8u2HxJQrJObFqpvLqQhkEKh7acizOZuJG/Q3V5294RFENhOS1oUMLSF",
	"hkIpbX9AFdciimXJf2H2H5XZkyyd7pK4SWnpF3Evu/PMPDPPc6uHPFRxqhJIrOHNh9yEexALf7kjdzqQ",
	"WLpMtUpBWwn+hYzoNwITaplaqRLe5Pg7znCCZzjCqXuCMzfEFwwneIpjnLkjnLiv8tfuCOfugOEI/1y8",
	"GvEabysdC8ubPMtkxGvc9lPgTW6slkmHD2o8M6ATEUMF8lM8d8ebAWFfxGmX8v2SVjxde8/wexzhM7rB",
	"EW+VwAY1ruFBJjVEtNvncwm/Wq7u3YfQUm63eguaNhL7Fef4zA2pehwTGc8ZTvMc3JDXNliNhBUVQX7A",
	"Ec48n2PmDlcR3XEpQgzGiE4VRb/hGM/coTvKQ1CQb339eZgS27FSVT3+GUcUxB3gPN9NZRV5L3NZoguI",
	"rt38cUWmE7woF1rKMNUqBGMg2hVV1H/nDnCczwUFOvANn7sjPMNJOfrl9EXCwg0rY3g1ZC6VIuQXidxn",
	"tNVYEacVsOs4MrEf3FxhyMRCBzSBGJXpEHbFUnnvamjzJn+nvpJpfaHR+lKgRLLQHbD5NlOpkXUFuCG7",
	"wfAC5zh1j9xjL8oxTn2O0kJs/g5yXoLQWvT9/ZKCV3bljVpQHiZ6JJO2IiwrbZfe7WSRtOwz0D0ZUpAe",
	"aJPjN7aCrYByVCkkIpW8yd/bamwFJCRh93zVdT+d/jJVxreAJCaohDsRb/JPlbG38jW5T4CxH6moTytD",
	"ldhF30SadmXot9XvG4JfemvZT/9D5Rds8g9ac4Ijd4ATnNKAjL2Zn+cbKqzyjZ2C4SlO3TH75G61Utbz",
	"2hNp2n+9Ty85aP0TlvO6/Eo8/Cu6veaG11+i3Or2/u/EvGqo1Rn4ByZVicnHfDvYfguZGSts5q/Wp0uE",
	"IaQWosrpLtR/ta/EcsjWMRajuWso69YVqSjS7S2HXSY7qPGbQVDuyp2kJ7oyYgtj8uu2Pyyv+1wpFouk",
	"zxZ2R4Ami2Oh++Rx2b2uNHts5w7rqg5VKTq+kKK3tmhXvQ3gHaADVR/iXy5HdeKO3BM/u+7QH4NOF76w",
	"qbzSOalowLfBfkyQZNpaxGBBU24l5J8IGSfuMY7JivAE5wUofMGu4TmOyB5xgufuEZ6zRhBcJ91QhAcZ",
	"6D6v8fzYybsylpbX1sYrgrbIupY3t4Maj8W+jLOYNxsB3clkcVf+yA9apbEO3mKsQ5VVnj6r6qcffI4n",
	"5GcLo5i5oft6g5iiATeCVtVJZfWhvJLL5IfkCo/JeS3n/yOO8II+IO6bZaL0l2JKvaJhKia5XZXkVYR1",
	"VxrLVJtpCElhSz3U+PvV+rL0R6DLDOgeaAZaK72hnttgi9FYO5/Xl6qItvt4+SBnusubvC5SWe816oJW",
	"80Fr8FcAAAD//+8KcimrDQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
