// Package openapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen version v1.16.3 DO NOT EDIT.
package openapi

import (
	"bytes"
	"compress/gzip"
	"encoding/base64"
	"fmt"
	"net/url"
	"path"
	"strings"
	"time"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// AIAgent defines model for AIAgent.
type AIAgent struct {
	// Id Уникальный идентификатор агента
	Id openapi_types.UUID `json:"id"`

	// Username Имя агента
	Username string `json:"username"`
}

// PostEventsJSONBody defines parameters for PostEvents.
type PostEventsJSONBody struct {
	// Data Данные события
	Data *struct {
		// Message Текст сообщения
		Message string `json:"message"`

		// Mood Настроение агента для ML обработки
		Mood *string `json:"mood,omitempty"`
	} `json:"data,omitempty"`

	// EventType Тип события для ML обработки
	EventType   *string  `json:"event_type,omitempty"`
	SourceAgent *AIAgent `json:"source_agent,omitempty"`

	// TargetAgents ИИ агент(ы) - получатели сообщения
	TargetAgents *[]AIAgent `json:"target_agents,omitempty"`

	// Timestamp Время события
	Timestamp *time.Time `json:"timestamp,omitempty"`
}

// PostEventsJSONRequestBody defines body for PostEvents for application/json ContentType.
type PostEventsJSONRequestBody PostEventsJSONBody

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// Publish AI log
	// (POST /events)
	PostEvents(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PostEvents converts echo context to params.
func (w *ServerInterfaceWrapper) PostEvents(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PostEvents(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.POST(baseURL+"/events", wrapper.PostEvents)

}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/5RUzWrbShR+FXHuXdwLipVwd9r5QheGFApdhhAm0ok9QdJMZ0amJhgct1BKCoG2i2y6",
	"aR+gShuDGsfOK5x5ozKjOH8WhG6EpPP3zfm+b44gEbkUBRZGQ3wEOhlgzvxrt9ftY2Hcq1RCojIcfYCn",
	"7pmiThSXhosCYqBvtKCaLqmiuf1AC3tCvwKq6YJmtLBTqu3bJmyntLSTgCr6eROqIIQDoXJmIIay5CmE",
	"YEYSIQZtFC/6MA6h1KgKlmPL5DO6sqePG+JrlsvM4d1xGWf34gF9oorO3QdVsLs2bByCwlclV5i6ao/n",
	"dvxdutg/xMTA2OXz4kA4ZIabzMW6ZcpN8BLVkCcIIQxR6QbtVmezs+kOJCQWTHKI4b/OVmcTQpDMDPx+",
	"Ixyu6JBCewLc+pk7cC+FGF4IbZ41OQ1W1OZ/kY5cZiIKc8MakzLjiS+LDrUbv+J3ndOUGday289U0cKz",
	"OQvsMS3p3J54Nk8d4AcdctSa9dsI+kozurTHdtq0cE3e++03bR5Q9d3l/KDKTqimeUDXNPOCumoKWugK",
	"IReiTZFfqHJD7YSWTTHNHqgkoAua29Pg+XbgMU28KpZ2SpdUP8I1YFKOntbKagfrKgnBk7rX/G5ZUU3X",
	"jzb8FL61PWhRqgT32Mq1fys8gBj+iu4sHt34O1qZexyCYaqPpinTrf66755/7Mm/wYYjZklz+8a+85ae",
	"0Zzqdnq5wVz/CZzmWEwpNvLfPEdtWC5boH20E5p5+6+J8/ZGSZnBDdcE2thrMfMdoUaV6H9oKQrtlFCU",
	"WRaCLvOcqZFzYrmfcT0Iur0gE303gfW9YLq9wJ8o2BZ9Dbu+sUblLgKId46gVBnEEDHJo+FWxNx9AePd",
	"8e8AAAD//4kEC2mPBQAA",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
