openapi: 3.1.0

info:
  title: Error Contract
  version: 1.0.0

paths: {}

components:
  schemas:

    ErrorCode:
      type: string
      description: >
        Application specific error codes.

        A - Authentication
        S - Signup
        L - Login
        AT - Access Token
        RT - Refresh Token
        R - Authorization

      oneOf:
        - const: A-1000
          description: Internal error

        - const: A-S1001
          description: Invalid signup credentials

        - const: A-L1001
          description: Invalid login credentials
        - const: A-L1002
          description: Account banned
        - const: A-L1003
          description: Too many login attempts
          
        - const: A-AT1001
          description: Access token expired
        - const: A-AT1002
          description: Access token signature invalid

        - const: A-RT1001
          description: Refresh token expired
        - const: A-RT1002
          description: Refresh token invalid
        
        - const: A-R1001
          description: Insufficient permissions
        - const: A-R1002
          description: Forbidden resource
        - const: A-R3003
          description: Role not allowed

    ErrorResponse:
      type: object
      required:
        - code
        - message
        - timestamp
      properties:
        code:
          $ref: '#/components/schemas/ErrorCode'
        message:
          type: string
          examples: 
            - Access token expired
        timestamp:
          type: string
          format: date-time
        traceId:
          type: string
          examples: 
            - 6f8c2d1e